const storys = [
  {
    "storyTitle": "Ba nàng công chúa",
    "storyContent":
        "Xưa kia, có một vị vua, ông cai quản đất nước của mình vô cùng tốt, dân chúng cơm no áo ấm, an cư lạc nghiệp, cuốc sống rất hạnh phúc. Nhà vua có ba nàng công chúa nhất mực xinh đẹp, ba nàng công chúa ngay từ khi sinh ra đã có một loại sức mạnh thần kỳ, đó là khi họ khóc nước mắt rơi xuống sẽ hóa thành những viên kim cương óng ánh.Một hôm, nhà vua phát hiện thấy rằng tuổi mình đã cao, sức khỏe đã yếu mà vẫn chưa có người nào để truyền ngôi vị, các nàng công chúa không có ai chăm sóc, vì vậy nhà vua liền chiêu cáo thiên hạ tìm chồng cho các công chúa. Một tháng sau, trong lâu đài của nhà vua chật ních các hoàng tử, kỵ sĩ và những người giàu có đến từ khắp nơi trên thế giới, tất cả họ đều là những chàng trai kiệt xuất, khôi ngô tuấn tú, diện mạo phi phàm. Họ tràn đầy tự tin tiến vào lâu đài chờ đợi sự lựa chọn từ các nàng công chúa. Giữa trưa, nhà vua dẫn theo ba nàng công chúa đi vào cung điện, để chào đón sự có mặt của những vị khách từ phương xa tới, nàng công chúa lớn đã hát một bài hát, giọng hát trong vắt của nàng giống như âm thanh của thiên nhiên. Nàng công chúa thứ hai thì nhảy một điệu nhảy, những bước nhảy của nàng uyển chuyển nhẹ nhàng, động tác đẹp mỹ diệu. Còn nàng tiểu công chúa nhỏ tuổi nhất, khẽ nở một nụ cười nhẹ nhàng rồi trốn sau lưng nhà vua mà không ra… Nhà vua lúng túng khó xử, giải thích với mọi người và mong mọi người bỏ qua cho, tiểu công chúa từ khi sinh ra đã không nói chuyện với ai và rất sợ người lạ. Để lấy lòng các nàng công chúa, mọi người lần lượt thể hiện tài năng xuất chúng của mình. Có người ở đó vẽ tranh, làm thơ tặng cho nàng công chúa lớn, có người vì công chúa thứ hai mà múa kiếm, thể hiện tài phi ngựa, chỉ có rất ít người dâng bảo vật quý báu tặng cho nàng tiểu công chúa. Hai nàng công chúa lớn đều rất vui vẻ đồng thời cũng dần dần có được lựa chọn của mình, chỉ có tiểu công chúa vẫn im lặng trốn ở đằng sau lưng nhà vua. Nàng công chúa lớn nhất cuối cùng đã lựa chọn một hoàng tử, vị hoàng tử tài năng xuất chúng này đã hứa hẹn với nàng: “Ta sẽ vì nàng mà chinh phục cả thế giới này, trên mỗi tòa thành chinh phục được, ta sẽ khắc tên của nàng.”",
  },
  {
    "storyTitle": "Nàng công chúa và hạt đậu",
    "storyContent":
        "Xưa kia, có một vị vua, ông cai quản đất nước của mình vô cùng tốt, dân chúng cơm no áo ấm, an cư lạc nghiệp, cuốc sống rất hạnh phúc. Nhà vua có ba nàng công chúa nhất mực xinh đẹp, ba nàng công chúa ngay từ khi sinh ra đã có một loại sức mạnh thần kỳ, đó là khi họ khóc nước mắt rơi xuống sẽ hóa thành những viên kim cương óng ánh.Một hôm, nhà vua phát hiện thấy rằng tuổi mình đã cao, sức khỏe đã yếu mà vẫn chưa có người nào để truyền ngôi vị, các nàng công chúa không có ai chăm sóc, vì vậy nhà vua liền chiêu cáo thiên hạ tìm chồng cho các công chúa. Một tháng sau, trong lâu đài của nhà vua chật ních các hoàng tử, kỵ sĩ và những người giàu có đến từ khắp nơi trên thế giới, tất cả họ đều là những chàng trai kiệt xuất, khôi ngô tuấn tú, diện mạo phi phàm. Họ tràn đầy tự tin tiến vào lâu đài chờ đợi sự lựa chọn từ các nàng công chúa. Giữa trưa, nhà vua dẫn theo ba nàng công chúa đi vào cung điện, để chào đón sự có mặt của những vị khách từ phương xa tới, nàng công chúa lớn đã hát một bài hát, giọng hát trong vắt của nàng giống như âm thanh của thiên nhiên. Nàng công chúa thứ hai thì nhảy một điệu nhảy, những bước nhảy của nàng uyển chuyển nhẹ nhàng, động tác đẹp mỹ diệu. Còn nàng tiểu công chúa nhỏ tuổi nhất, khẽ nở một nụ cười nhẹ nhàng rồi trốn sau lưng nhà vua mà không ra…",
  },
  {
    "storyTitle": "Nàng công chúa ống tre",
    "storyContent":
        "Xưa kia, có một vị vua, ông cai quản đất nước của mình vô cùng tốt, dân chúng cơm no áo ấm, an cư lạc nghiệp, cuốc sống rất hạnh phúc. Nhà vua có ba nàng công chúa nhất mực xinh đẹp, ba nàng công chúa ngay từ khi sinh ra đã có một loại sức mạnh thần kỳ, đó là khi họ khóc nước mắt rơi xuống sẽ hóa thành những viên kim cương óng ánh.Một hôm, nhà vua phát hiện thấy rằng tuổi mình đã cao, sức khỏe đã yếu mà vẫn chưa có người nào để truyền ngôi vị, các nàng công chúa không có ai chăm sóc, vì vậy nhà vua liền chiêu cáo thiên hạ tìm chồng cho các công chúa. Một tháng sau, trong lâu đài của nhà vua chật ních các hoàng tử, kỵ sĩ và những người giàu có đến từ khắp nơi trên thế giới, tất cả họ đều là những chàng trai kiệt xuất, khôi ngô tuấn tú, diện mạo phi phàm. Họ tràn đầy tự tin tiến vào lâu đài chờ đợi sự lựa chọn từ các nàng công chúa. Giữa trưa, nhà vua dẫn theo ba nàng công chúa đi vào cung điện, để chào đón sự có mặt của những vị khách từ phương xa tới, nàng công chúa lớn đã hát một bài hát, giọng hát trong vắt của nàng giống như âm thanh của thiên nhiên. Nàng công chúa thứ hai thì nhảy một điệu nhảy, những bước nhảy của nàng uyển chuyển nhẹ nhàng, động tác đẹp mỹ diệu. Còn nàng tiểu công chúa nhỏ tuổi nhất, khẽ nở một nụ cười nhẹ nhàng rồi trốn sau lưng nhà vua mà không ra…",
  },
  {
    "storyTitle": "Tấm cám",
    "storyContent":
        "Xưa kia, có một vị vua, ông cai quản đất nước của mình vô cùng tốt, dân chúng cơm no áo ấm, an cư lạc nghiệp, cuốc sống rất hạnh phúc. Nhà vua có ba nàng công chúa nhất mực xinh đẹp, ba nàng công chúa ngay từ khi sinh ra đã có một loại sức mạnh thần kỳ, đó là khi họ khóc nước mắt rơi xuống sẽ hóa thành những viên kim cương óng ánh.Một hôm, nhà vua phát hiện thấy rằng tuổi mình đã cao, sức khỏe đã yếu mà vẫn chưa có người nào để truyền ngôi vị, các nàng công chúa không có ai chăm sóc, vì vậy nhà vua liền chiêu cáo thiên hạ tìm chồng cho các công chúa. Một tháng sau, trong lâu đài của nhà vua chật ních các hoàng tử, kỵ sĩ và những người giàu có đến từ khắp nơi trên thế giới, tất cả họ đều là những chàng trai kiệt xuất, khôi ngô tuấn tú, diện mạo phi phàm. Họ tràn đầy tự tin tiến vào lâu đài chờ đợi sự lựa chọn từ các nàng công chúa. Giữa trưa, nhà vua dẫn theo ba nàng công chúa đi vào cung điện, để chào đón sự có mặt của những vị khách từ phương xa tới, nàng công chúa lớn đã hát một bài hát, giọng hát trong vắt của nàng giống như âm thanh của thiên nhiên. Nàng công chúa thứ hai thì nhảy một điệu nhảy, những bước nhảy của nàng uyển chuyển nhẹ nhàng, động tác đẹp mỹ diệu. Còn nàng tiểu công chúa nhỏ tuổi nhất, khẽ nở một nụ cười nhẹ nhàng rồi trốn sau lưng nhà vua mà không ra…",
  },
  {
    "storyTitle": "Sọ dừa",
    "storyContent":
        "Chàng trai Vũng Tàu có biệt danh \"sọ dừa\" vì 35 tuổi mà thân hình vẫn như trẻ con còn cô gái làm công nhân ở Hà Nội. Tình yêu đã đưa họ về chung một nhà.Đồng hồ điểm 20h, Phạm Hữu Thọ lăn tròn trên đệm xuống sàn nhà, dùng lực đẩy đầu về phía tủ lạnh. Anh dùng cánh tay phải mềm oặt để bấm công tắc nồi cơm. Xong xuôi, anh tiếp tục lăn về phía chiếc điện thoại, bấm phím nhắn tin: \"Vợ về chưa?, Chồng cắm cơm rồi\".Vừa ra khỏi cổng một khu công nghiệp ở Bắc Thăng Long (Đông Anh, Hà Nội), chị Phạm Thanh Hoa gọi luôn cho chồng: \"Em đang về rồi. Chờ 10 phút em mua cho hộp cà phê. Anh cần gì nữa không?\". Anh Thọ nhấp nháy đôi mắt, đùa: \"Chỉ cần vợ mập thôi\".",
  },
  {
    "storyTitle": "Cây tre trăm đốt",
    "storyContent":
        "Xưa kia, có một vị vua, ông cai quản đất nước của mình vô cùng tốt, dân chúng cơm no áo ấm, an cư lạc nghiệp, cuốc sống rất hạnh phúc. Nhà vua có ba nàng công chúa nhất mực xinh đẹp, ba nàng công chúa ngay từ khi sinh ra đã có một loại sức mạnh thần kỳ, đó là khi họ khóc nước mắt rơi xuống sẽ hóa thành những viên kim cương óng ánh.Một hôm, nhà vua phát hiện thấy rằng tuổi mình đã cao, sức khỏe đã yếu mà vẫn chưa có người nào để truyền ngôi vị, các nàng công chúa không có ai chăm sóc, vì vậy nhà vua liền chiêu cáo thiên hạ tìm chồng cho các công chúa. Một tháng sau, trong lâu đài của nhà vua chật ních các hoàng tử, kỵ sĩ và những người giàu có đến từ khắp nơi trên thế giới, tất cả họ đều là những chàng trai kiệt xuất, khôi ngô tuấn tú, diện mạo phi phàm. Họ tràn đầy tự tin tiến vào lâu đài chờ đợi sự lựa chọn từ các nàng công chúa. Giữa trưa, nhà vua dẫn theo ba nàng công chúa đi vào cung điện, để chào đón sự có mặt của những vị khách từ phương xa tới, nàng công chúa lớn đã hát một bài hát, giọng hát trong vắt của nàng giống như âm thanh của thiên nhiên. Nàng công chúa thứ hai thì nhảy một điệu nhảy, những bước nhảy của nàng uyển chuyển nhẹ nhàng, động tác đẹp mỹ diệu. Còn nàng tiểu công chúa nhỏ tuổi nhất, khẽ nở một nụ cười nhẹ nhàng rồi trốn sau lưng nhà vua mà không ra…",
  }
];
